version: 2
project_name: sshclient-wasm

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: sshclient
    main: ./main.go
    binary: sshclient
    goos:
      - js
    goarch:
      - wasm
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    # We only build for js/wasm and we can just have the single WASM binary in
    # the dist directory.
    no_unique_dist_dir: true
    hooks:
      post:
        - sh -c 'cp "$(go env GOROOT)/lib/wasm/wasm_exec.js" dist/wasm_exec.js'
        - pnpm build:ts

archives:
  - id: wasm-archive
    formats:
      - tar.gz
    files:
      - sshclient.wasm
      - wasm_exec.js
      - lib/**/*
      - package.json
      - README.md
      - LICENSE

release:
  github:
    owner: VerdigrisTech
    name: sshclient-wasm
  prerelease: auto

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'