version: 2.1

orbs:
  node: circleci/node@7.1.1

executors:
  golang-node:
    docker:
      - image: cimg/go:1.24-node
    resource_class: medium

commands:
  npm-auth:
    description: |
      Sets up npm authentication
    steps:
      - run:
          name: Set npm token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

jobs:
  build:
    executor: golang-node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: pnpm
      - run:
          name: Install Go dependencies
          command: go mod download
      - run:
          name: Build WASM
          command: pnpm build:wasm:dev
      - persist_to_workspace:
          root: .
          paths:
            - dist/
      - store_artifacts:
          path: dist/

  release:
    executor: golang-node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - npm-auth
      - node/install-packages:
          pkg-manager: pnpm
      - run:
          name: Version packages and push tags
          command: |
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@verdigris.co"
            pnpm changeset version
            git push origin main
      - run:
          name: Publish to NPM (triggers prepublishOnly build)
          command: pnpm changeset publish
      - run:
          name: Sync tags
          command: git push --follow-tags origin main

workflows:
  test-and-build:
    jobs:
      - build
      - release:
          context:
            - npmjs.com
            - github
          requires:
            - build
          filters:
            branches:
              only: main